Repository googleapis/python-cloudbuild, pull requests merged in 2021-04, with the labels that each got.

#73 feat: Add `SecretManager`-related resources and messages for corresponding integration.
  .pre-commit-config.yaml
  UPGRADING.md
  google/cloud/devtools/cloudbuild/__init__.py
  google/cloud/devtools/cloudbuild_v1/__init__.py
  google/cloud/devtools/cloudbuild_v1/proto/cloudbuild.proto
  google/cloud/devtools/cloudbuild_v1/services/cloud_build/async_client.py
  google/cloud/devtools/cloudbuild_v1/services/cloud_build/client.py
  google/cloud/devtools/cloudbuild_v1/services/cloud_build/transports/base.py
  google/cloud/devtools/cloudbuild_v1/services/cloud_build/transports/grpc.py
  google/cloud/devtools/cloudbuild_v1/services/cloud_build/transports/grpc_asyncio.py
  google/cloud/devtools/cloudbuild_v1/types/__init__.py
  google/cloud/devtools/cloudbuild_v1/types/cloudbuild.py
  noxfile.py
  scripts/fixup_cloudbuild_v1_keywords.py
  setup.py
  synth.metadata
  testing/constraints-3.6.txt
  tests/unit/gapic/cloudbuild_v1/test_cloud_build.py
Labels: api: cloudbuild, cla: yes, context: full

#79 chore: start tracking obsolete files
  synth.metadata
Labels: api: cloudbuild, cla: yes, context: full

#82 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: full

#84 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: cloudbuild, cla: yes, context: full, samples

#86 chore: Re-generated to pick up changes from synthtool
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: cloudbuild, cla: yes, context: full

#88 chore: prevent normalization of semver versioning
  setup.py
Labels: api: cloudbuild, automerge, cla: yes

#89 chore(revert): revert preventing normalization
  setup.py
Labels: api: cloudbuild, automerge, cla: yes
