Repository googleapis/python-cloudbuild, pull requests merged in 2021-03, with the labels that each got.

#66 test: install pyopenssl for mtls testing
  noxfile.py
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes, context: full

#68 chore: add pre-commit-config to renovate ignore paths
  renovate.json
  synth.metadata
Labels: api: cloudbuild, cla: yes, context: full

#52 feat: add `from_service_account_info`
  docs/cloudbuild_v1/cloud_build.rst
  docs/cloudbuild_v1/services.rst
  docs/cloudbuild_v1/types.rst
  google/cloud/devtools/cloudbuild_v1/proto/cloudbuild.proto
  google/cloud/devtools/cloudbuild_v1/services/cloud_build/async_client.py
  google/cloud/devtools/cloudbuild_v1/services/cloud_build/client.py
  google/cloud/devtools/cloudbuild_v1/services/cloud_build/pagers.py
  google/cloud/devtools/cloudbuild_v1/services/cloud_build/transports/grpc.py
  google/cloud/devtools/cloudbuild_v1/services/cloud_build/transports/grpc_asyncio.py
  google/cloud/devtools/cloudbuild_v1/types/cloudbuild.py
  synth.metadata
  tests/unit/gapic/cloudbuild_v1/__init__.py
  tests/unit/gapic/cloudbuild_v1/test_cloud_build.py
Labels: api: cloudbuild, automerge, cla: yes, context: full, context: partial

#69 docs: Adding samples
  samples/snippets/noxfile.py
  samples/snippets/quickstart.py
  samples/snippets/quickstart_test.py
  samples/snippets/requirements-test.txt
  samples/snippets/requirements.txt
Labels: api: cloudbuild, cla: yes
