Repository googleapis/python-cloudbuild, pull requests merged in 2021-05, with the labels that each got.

#93 [CHANGE ME] Re-generated to pick up changes from self.
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  noxfile.py
  synth.metadata
Labels: api: cloudbuild, cla: yes, context: none

#94 chore: add library type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudbuild, automerge, cla: yes

#97 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
  synth.py
Labels: api: cloudbuild, cla: yes

#99 chore: Update Owl bot begin-after-commit-hash
  .github/.OwlBot.yaml
Labels: api: cloudbuild, automerge, cla: yes

#101 fix(deps): add packaging requirement
  setup.py
  testing/constraints-3.6.txt
Labels: api: cloudbuild, automerge, cla: yes

#100 chore: release 3.2.1
  CHANGELOG.md
  setup.py
Labels: api: cloudbuild, autorelease: pending, cla: yes

#104 chore: add cicd (devplat) team to codeowners
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: cloudbuild, cla: yes
