Repository googleapis/python-cloudbuild, pull requests merged in 2022-04, with the labels that each got.

#255 chore: allow releases from previous major versions
  .github/release-please.yml
  owlbot.py
Labels: api: cloudbuild, size: s

#256 chore: use black 22.3.0
  .gitignore
  docs/conf.py
  google/cloud/devtools/cloudbuild_v1/gapic/cloud_build_client.py
  google/cloud/devtools/cloudbuild_v1/proto/cloudbuild_pb2.py
  google/cloud/devtools/cloudbuild_v1/proto/cloudbuild_pb2_grpc.py
  noxfile.py
Labels: api: cloudbuild, size: l

#268 chore(quickstart): clarify private pools instructions
  samples/snippets/quickstart.py
Labels: api: cloudbuild, size: xs
